### PR TITLE
random case SNI

### PR DESCRIPTION
**Pull request by mosajjal**

### CODE REVIEW

**Comment by mosajjal** [comment]
before merging this, need to verify if `utls` itself supports non-lowercase SNI:
https://github.com/refraction-networking/utls#roller

if it doesn't, the issue needs to be fixed there before merging this :)

**Comment by mosajjal** [comment]
tested with this config:
```json
{
  "inbounds": [
    {
      "type": "http",
      "listen_port": 1081
    }
  ],
  "outbounds": [
    {
      "type": "http",
      "server": "127.0.0.1",
      "server_port": 8443,
      "tls": {
        "enabled": true,
        "disable_sni": false,
        "server_name": "gOogle.com",
        "insecure": true
      }
    }
  ]
}
```
and it works:
image

though I don't think this actually uses the PR I submitted, meaning the code on its own should work with any uppercase or lower-case letters.

**Comment by hiddify-com** [comment]
This means that your code also works

**Comment by hiddify-com** [comment]
It would be great if you can add more tests

```
{
  "inbounds": [
    {
      "type": "http",
      "listen_port": 1081
    }
  ],
  "outbounds": [
    {
      "type": "http",
      "server": "127.0.0.1",
      "server_port": 8443,
      "tls": {
        "enabled": true,
        "disable_sni": false,
        "server_name": "gOogle.com",
        "insecure": true,
"utls": {
    "enabled": true,
    "fingerprint": "firefox"
  },
"mixedcase_sni": true
      }
    }
  ]
}
```

**Pull request merged**
